server {
    listen 3001;
    server_name localhost;

 # Match the prefix passed by your reverse proxy
    location /iphone/ {
        alias /usr/share/nginx/html/;
        index index.html index.htm;
        try_files $uri $uri/ /iphone/index.html;
    }

    # Fallback default rule
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }


}
