# Stage 1: Build the React application
FROM node:20-alpine AS build
WORKDIR /workspace

# Copy package configurations and install dependencies
COPY ./PhotoGlobe/package*.json ./

# Receive the argument from docker-compose.yml
ARG VITE_BASE_URL_LOCAL
ARG VITE_BASE_URL_PUBLIC
ARG VITE_CESIUM_KEY
ARG VITE_GOOGLE_KEY
ARG VITE_OS_KEY
ARG VITE_TT_KEY
# Expose it to the Node/Vite build process
ENV VITE_BASE_URL_LOCAL=$VITE_BASE_URL_LOCAL
ENV VITE_BASE_URL_PUBLIC=$VITE_BASE_URL_PUBLIC
ENV VITE_CESIUM_KEY=$VITE_CESIUM_KEY
ENV VITE_GOOGLE_KEY=$VITE_GOOGLE_KEY
ENV VITE_OS_KEY=$VITE_OS_KEY
ENV VITE_TT_KEY=$VITE_TT_KEY


RUN npm ci

# Copy the entire frontend source code and compile it
COPY ./PhotoGlobe/ ./
RUN npm run build



# Stage 2: Serve the compiled static assets with Nginx
FROM nginx:alpine
# Copy the compiled build folder into Nginx's public directory
COPY --from=build /workspace/dist /usr/share/nginx/html

# FIX 1: Copy your local nginx.conf to apply the /map routing fix
COPY nginx.conf /etc/nginx/conf.d/default.conf

# FIX 2: Change this from 80 to 3000 to match your app configuration
EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]
