log_format image_api_logs '$remote_addr - $remote_user [$time_local] '
                          '"$request" $status $body_bytes_sent '
                          'API_KEY_RECEIVED: "$http_x_api_key"';

server {
    listen 3500;
    server_name 192.168.0.202; # Your Image Server VM IP

    # Allows large photo uploads from your Web API VM to this server
    client_max_body_size 100M; 

    # Force Nginx to write directly to Docker's stdout/stderr streams
    #access_log /dev/stdout image_api_logs;
    #error_log /dev/stderr warn;

    # This runs for every single endpoint on this server automatically
    if ($http_x_api_key != "PreventHotLinking") {
        return 444; 
    }

    # 1. ROUTE FOR FAST THUMBNAILS
    location /uploads/thumbs/ {
        alias /var/www/photo-app/uploads/thumbs/;
        expires 30d;
        add_header Cache-Control "public, no-transform";

        # Explicitly allow your proxy IPs
        allow 192.168.0.200;
        allow 172.18.0.2;
    
        # Drop connections from any other IP address
        deny all;
    }

      # 1. ROUTE FOR FAST SMALL IMAGES
    location /uploads/small/ {
        alias /var/www/photo-app/uploads/small/;
        expires 30d;
        add_header Cache-Control "public, no-transform";

        # Explicitly allow your proxy IPs
        allow 192.168.0.200;
        allow 172.18.0.2;
    
        # Drop connections from any other IP address
        deny all;
    }

    # 2. MAIN IMAGES
     location /uploads/ {
        alias /var/www/photo-app/uploads/;
        expires 30d;
        add_header Cache-Control "public, no-transform";
    
        # Explicitly allow your proxy IPs
        allow 192.168.0.200;
        allow 172.18.0.2;
    
        # Drop connections from any other IP address
        deny all;
    }


    location /uploads/hello {
        default_type text/plain;
        if ($arg_name = "") {
           return 200 "Hello!";
        }
        return 200 "Hello!, $arg_name. Api update test number: 6";
    }

}
