FROM node:22-alpine

WORKDIR /app

# Copy package configurations first to leverage caching
COPY package*.json ./

RUN npm install

# Copy all project source code
COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]