name: Deploy API Server Changes

on:
  workflow_call:
    inputs:
      target_host:
        required: true
        type: string
        description: "The specific VM hostname to target (e.g., VM200)"
      api_target_ip:
        required: true
        type: string
        description: "The API backend IP address for internal configuration"
      api_user:
        required: true
        type: string
        description: "The API backend user"

jobs:
  deploy:
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5 

      - name: Copy API Deployment and Code to Proxmox
        run: |
          ssh -i /root/.ssh/runner-vm  -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "${{ inputs.api_user }}@${{ inputs.api_target_ip }}" "rm -rf ~/react-photo-app/api-server"
          
          # Added quotes around the target macro to hide the path colon from YAML
          scp -i /root/.ssh/runner-vm  -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r api-server/ "${{ inputs.api_user }}@${{ inputs.api_target_ip }}":~/react-photo-app/api-server

      - name: Copy Nginx to Proxmox
        run: |
          ssh -i /root/.ssh/runner-vm  -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "${{ inputs.api_user }}@${{ inputs.api_target_ip }}" "rm -rf ~/react-photo-app/nginx.conf"
          
          # Added quotes around the target macro to hide the path colon from YAML
          scp -i /root/.ssh/runner-vm  -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r api-server/nginx.conf "${{ inputs.api_user }}@${{ inputs.api_target_ip }}":~/react-photo-app/nginx.conf

      - name: Generate Environmental Payload Locally
        env:
          API_SECRET: ${{ secrets.MONGODB_KEY }}
        run: |
          echo "MONGODB_KEY=$API_SECRET" > local.env

      - name: Copy Environment File to Proxmox
        run: |
          scp -i /root/.ssh/runner-vm  -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null local.env "${{ inputs.api_user }}@${{ inputs.api_target_ip }}":~/react-photo-app/api-server/.env

      - name: Remote Restart via SSH
        run: 'ssh -i /root/.ssh/runner-vm  -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null "${{ inputs.api_user }}@${{ inputs.api_target_ip }}" "cd ~/react-photo-app/api-server && docker compose down && docker compose up -d --build"'
