name: " 🟢 Deploy/Update Server Set 200 Infrastructure"

on:
  workflow_dispatch:

jobs:
  terraform:
    name: "Run Terraform"
    runs-on: self-hosted

    defaults:
      run:
        working-directory: ./1-infrastructure/terraform

    steps:
      # TERRAFORM
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Terraform Init
        run: |
          # Dynamically inject the correct path into the backend during initialization
          terraform init -backend-config="path=/var/lib/terraform/server-set-${{ env.TF_VAR_set_prefix }}-infra.tfstate"
        working-directory: ./1-infrastructure/terraform
        env:
          TF_VAR_set_prefix: "200" # Or change to "210" for your other set

      - name: Generate Secure TFVars
        run: |
          cat << 'EOF' > secret.auto.tfvars
          proxmox_endpoint = "${{ secrets.PROXMOX_ENDPOINT }}"
          proxmox_token    = "${{ secrets.PROXMOX_TOKEN }}"
          server_passwords = {
              "VM200" = "${{ secrets.VM200_PASS }}",
              "VM201" = "${{ secrets.VM201_PASS }}",
              "VM202" = "${{ secrets.VM202_PASS }}",
          }
          EOF

      - name: Terraform Plan
        run: terraform plan -var="set_prefix=200" -out=tfplan

      - name: Terraform Apply
        run: terraform apply -var="set_prefix=200" -auto-approve 

      # ANSIBLE  -  Run scriots listed in site.yml
      - name: Run Ansible Configuration Playbook
        working-directory: ./2-system/ansible  
        run: |
      
          # Configure Ansible flags globally to silence warnings and force color
          export ANSIBLE_HOST_KEY_CHECKING=False
          export ANSIBLE_FORCE_COLOR=True
          export ANSIBLE_PYTHON_INTERPRETER=auto_silent
      
          # 4. Run playbook forcing OpenSSH to ignore known_hosts entirely
          ansible-playbook -i inventory.ini site.yml \
            --private-key=~/.ssh/runner-vm \
            -e "global_group=hosts_200 proxy_group=proxy_200 api_group=api_200 image_group=image_server_200 deployment_user=svc " \
            --ssh-common-args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes'
        shell: /usr/bin/bash -e {0}


  call-child-proxy:
    needs: terraform
    uses: ./.github/workflows/cattle-config-proxy.yml
    with:
      target_host: "VM200"              # 🎯 Explicitly pass VM200 for the Set 200 pipeline
      api_target_ip: "10.10.10.200"     # 🎯 Explicitly pass the Set 200 API IP
      api_user: "svc"                   # 🎯 Explicitly pass the user
    secrets: inherit

  #call-child-api:
  #  needs: terraform
  #  uses: ./.github/workflows/deploy-api.yml
  #   with:
  #    target_host: "VM201"              # 🎯 Explicitly pass VM200 for the Set 200 pipeline
  #    api_target_ip: "10.10.10.201"     # 🎯 Explicitly pass the Set 200 API IP
  #    api_user: "svc"                   # 🎯 Explicitly pass the user
  #  secrets: inherit
    
