name: "🟢 Deploy/Update Server Set 20 Infrastructure"

on:
  workflow_dispatch:

jobs:
  terraform:
    name: "Run Terraform"
    runs-on: self-hosted

    defaults:
      run:
        working-directory: ./terraform

    steps:
      # TERRAFORM
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Terraform Init
        run: terraform init

      - name: Generate Secure TFVars
        run: |
          cat << 'EOF' > secret.auto.tfvars
          proxmox_endpoint = "${{ secrets.PROXMOX_ENDPOINT }}"
          proxmox_token    = "${{ secrets.PROXMOX_TOKEN }}"
          server_passwords = {
              "VM200" = "${{ secrets.VM200_PASS }}",
              "VM201" = "${{ secrets.VM201_PASS }}",
              "VM202" = "${{ secrets.VM202_PASS }}",
          }
          EOF

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan

      # ANSIBLE  -  Run scriots listed in site.yml
      - name: Run Ansible Configuration Playbook
        working-directory: ./ansible  
        env:
          HOST_0: "VM200"
          HOST_1: "VM201"
          HOST_2: "VM202"
        run: |
      
          # Configure Ansible flags globally to silence warnings and force color
          export ANSIBLE_HOST_KEY_CHECKING=False
          export ANSIBLE_FORCE_COLOR=True
          export ANSIBLE_PYTHON_INTERPRETER=auto_silent
      
          # 4. Run playbook forcing OpenSSH to ignore known_hosts entirely
          ansible-playbook -i inventory.ini site.yml \
            --private-key=~/.ssh/runner-vm \
            --ssh-common-args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes'
        shell: /usr/bin/bash -e {0}


  #call-child:
#    # Calls another YAML file in the same repository
#    needs: terraform
#    uses: ./.github/workflows/vm20-deploy-proxy.yml
#    secrets: inherit
