name: Deploy gatekeeper

on:
  push:
    branches: [ "main" ]
    paths:
      - 'gatekeeper/**'
      - ".github/workflows/deploy-gatekeeper.yml"
      
jobs:
  deploy:
    runs-on: [self-hosted, linux]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy Proxy Config Files to edge-proxy
        run: |
         # 1. Copy files into /opt/nginx-proxy/
         scp -i /root/.ssh/runner-vm -o StrictHostKeyChecking=no gatekeeper/* ${{ secrets.GATEKEEPER_USER }}@${{ secrets.GATEKEEPER_HOST }}:/opt/nginx-proxy/
  

      - name: Start Nginx Proxy Container edge-proxy
        run: |
        
          ssh -i /root/.ssh/runner-vm -o StrictHostKeyChecking=no "${{ secrets.GATEKEEPER_USER }}@${{ secrets.GATEKEEPER_HOST }}" "
            cd /opt/nginx-proxy && 
            docker compose down && 
            docker compose up -d --force-recreate
          "
