name: Deploy Image Server

on:
  push:
    branches:
      - main
    paths:
      - "image-server/**"
      - ".github/workflows/deploy-infra.yml"

jobs:
  deploy:
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Copy Image-Server Server Files to Proxmox
        run: |
          # Use your local SSH key to securely push the codebase onto the target server over your LAN
          scp -i /home/github-runner/.ssh/runner-to-vm2 -o StrictHostKeyChecking=no -r image-server/ ${{ secrets.VM2_USER }}@192.168.0.202:~/react-photo-app/

      - name: Remote Restart via SSH
        run: |
          # Remotely trigger Docker inside the target folder without checking out Git on the server
          ssh -i /home/github-runner/.ssh/runner-to-vm1 -o StrictHostKeyChecking=no "${{ secrets.VM2_USER }}@192.168.0.202" "
            cd ~/react-photo-app/image-server && 
            docker compose down &&
            docker compose up -d
          "
